[package]
name = "level"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bevy.workspace = true
bevy_ecs_tilemap = { version = "0.19.0", features = ["atlas"] }
bevy_light_2d = "0.9"
models = { path = "../models" }
dialog = { path = "../dialog" }
quest = { path = "../quest" }
rand = "0.10.2"
getrandom = { version = "0.4.3", features = ["wasm_js"] }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0"
