[package]
name = "dialog"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
bevy.workspace = true
keybinds = { path = "../keybinds" }
models = { path = "../models" }
serde = { version = "1.0.228", features = ["derive"] }
ron = "0.12.1"
rand = "0.10.1"
getrandom = { version = "0.4.2", features = ["wasm_js"] }
futures-lite = "2.6.1"
